---
abstract: 'Catmandu fixes for processing dates'
author:
  - 'Nicolas Franck, C<< <nicolas.franck at ugent.be> >>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Fix-Date
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  DateTime::TimeZone: 0
  Moo: 0
  Time::HiRes: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Fix-Date/issues
  homepage: https://github.com/LibreCat/Catmandu-Fix-Date
  repository: https://github.com/LibreCat/Catmandu-Fix-Date.git
version: 0.0122
